baseurl = "https://rdwrcode.github.io/b/"
theme = "vienna"
title = "Read.Write.Code"
languageCode = "en-us"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright <a href=\"https://github.com/rdwrcode\">rdwrcode</a> 2016. All Rights Reserved."

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "rdwrcode"
    github = "rdwrcode"
    #linkedin = "Your LinkedIn username"
    #googleplus = "Your Google+ user id"
    #facebook = "Your Facebook username"
    #stackoverflow = "Your Stackoverflow user id (number)"
    #keybase = "Your keybase.io username"
    #instagram = "Your Instagram username"
    # Disqus shortname
    #disqus = "Your disqus shortname"
    # Google Analytics API key.
    ga_api_key = "UA-89560048-1"
    # Mixpanel API key.
    #mixpanel_api_key = "Your Mixpanel API key"
    author = "rdwrcode"
    #avatar = "/path/to/avatar"
    contact = "mailto:rdwrcode@gmail.com"
    bio = "reader/writer/coder"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "notes on books, science, and programming"
    themecolor = "#666" # Defines the tab color in Chrome for Android.

